document:
  dsl: 1.0.0
  taskQueue: zigflow
  workflowType: catalog
  version: 0.0.1
input:
  schema:
    format: json
    document:
      type: object
      required:
        - message
      properties:
        message:
          type: string
do:
  - set:
      output:
        as:
          data: ${ . }
      set:
        message: ${ $input.message }
